env:
  global:
    - secure: "b+Uf638qHev+gn29EJ9FpQXKOR2bf8UgkrqKaEF3juKQeRrGV8AkLkFMYriEa8n6OwJK1lOqgcB0rABHvmv6UrFkHgRtUZvYTZJTadv79548L+YNOgOYe8vDEombTKHntlErvIcE5xV0YsW1ZBMKqPcqqyjLxjcf6LMbz5yFi0fRIHDKNqxnW/4uOpSFUIqUubSvSQsG/fkssmx1cTfsmLJ76Z2XODy4B3/+hsmXGKSZJ1ETeDpUpC/VKJAt30k/plFlDt+Injiz1GjvfwRPW1P0ti1bCtcRk/OFSZWngz50ipfnLcE6CUdaBV3zu6BTw0WHZl8wtD2GLeXW0SK5i6DoqZDiOECgeA5kp+OhmwNZUwBJNJRYaEyJHqWuZcFhjDd5Ll+TaeZIn3bsPPlVTdZAjxRAqrt/GwBSlSr3s12HwILBWwiXnpI61ddJ3BQ60z5YevA5KYx74gmo4wo25eO/VNzaQV/4s+XE60CW0HJYrG1K9PJZq51vQy9E7V6xtxRHiaw2UsXQGkWYQOufvQ8RQAxSH9KvZUGhLH6k9CgiRl06sB2Z40BQ9oJNIzH5L/qT1mjDWHNEjOLxypQp6WHbjtWgDEhLKjRCCXoxy6XW0Zcjg8aFVTcJOXPsLhTvts8v59mQ+Qzp4iwKgfp4Q5WzIJXgERWBYIU/ohufCVs="
    - HUGO_RELEASE=0.14

install: ./scripts/get_deps.sh

script: ./scripts/build_all.sh

deploy:
    skip_cleanup: true
    provider: script
    script: ./scripts/deploy.sh
