env:
  global:
    - secure: "JsNY1N8We06mJKP9+fOYIFPRX94lrtpBsD0Sxo2YbENcdk6jlh5WArMJVOMnSW/bsacr31mmYD7lYsBg3RSgMbQuOQ3EGRyRGMDPs2Bl4H6O/2osZZTqu9vwqPqZRn/0plRbuP4AuIuKzxOQ8iE7gAGQoRL021LnlSAZE8ExFRYLLOVX8jMaRB0JzKc/N+QWWzvfyK1Z2mkJA5wYKtS1Ajpgrimk4zFylh97K3S6QTXOuiuHu9G4yAACtVV+CcJNHxV8TxWS05UocwyiPgqOL11fjSwCUrfXWLQ/xOESRKGNYxYEW1GOscoJyGsmaViF3xF070q6exBbmWM638+/J/lov57M/3WGu1NO2KYVNRo6E7eL3pFU3s+X5PXUMojhb0Du4XAiNLJ7NBQ8V9XdZHB/OJKaYua40Gao+If01Nh9GcnPujNrpFRcDujl6l1HaUlGm4gmAnugCVue1a4yrqZwLGf0ZGZBxE2WQDzrkL5K1exmRVMfQKHs7C2OV1FU8T4GS+voq/+iHYipHNdj8e9+D+St1mLA7qA5PSrqt6WdPgJIjQ+KYBS71RfAY3PGUyqCS9xK9x2ha87neT4KHRKhWvUULUgPw9m6Lg/7mts7x+WUayZ/PwPGFvbgd2ylpjIHD//h3H+PxhYgFgnLu4Kl+5LEc/gD5WxwAH4Hr+8="
    - HUGO_RELEASE=0.14

install: ./scripts/get_deps.sh

script: ./scripts/build_all.sh

deploy:
    skip_cleanup: true
    provider: script
    script: ./scripts/deploy.sh
